---
- name: update cloud.cfg
  hosts: all
  tasks:
    - name: comment ipa server line
      lineinfile:
        path : /etc/ntp.conf
        regexp : '^jewelpaymentech.net'
        line : '#server identity.jewelpaymentech.net'

    - name: put aws ntp server details
      lineinfile:
        path : /etc/ntp.conf
        line : 'server 169.254.169.123 iburst'

    - name: restart ntp service
      service:
        name: ntp
        state: restarted

