---
- hosts: all
  become : yes
  tasks:
  - name: Check if reboot is required for Ubuntu
    stat:
      path: /var/run/reboot-required
    register: reboot_required_ubuntu
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Reboot Ubuntu
    reboot:
    when:
      - ansible_facts['distribution'] == "Ubuntu"
      - reboot_required_ubuntu.stat.exists

  - name: Check of reboot is required for CentOS
    shell: if [ $(rpm -q kernel|tail -n 1) != kernel-$(uname -r) ]; then echo 'reboot'; else echo 'no'; fi
    ignore_errors: true
    register: reboot_required_centos
    when: ansible_facts['distribution'] == "CentOS"

  - name: Reboot CentOS
    reboot:
    when:
      - ansible_facts['distribution'] == "CentOS"
      - reboot_required_centos.stdout.find("reboot") != -1
