---
- name: update cloud.cfg
  hosts: all
  tasks:
    - name: set preserve hostname to true
      lineinfile:
        path : /etc/cloud/cloud.cfg
        regexp : '^preserve_hostname:'
        line : 'preserve_hostname: true'

